-- Seed data is now applied directly from migrations (see
-- 20260310000002_metals.sql, 20260310000007_metal_categories.sql, and
-- 20260310000008_seed_metal_grades.sql). Those migrations create the
-- canonical set of categories and metals, and phase 2 of the multi-
-- tenancy migration stamps them with the Legacy company's id.
--
-- Add dev-only test data below (sample users, test receipts, etc.) as
-- needed. Any inserts into multi-tenant tables must include a
-- company_id — look up the Legacy row if you want to pile test data
-- there, e.g.:
--
--   insert into public.customers (name, phone, company_id) values
--     ('Test Customer', '555-0000',
--      (select id from public.companies where prefix = 'LEGAC-2026'));
