import { supabase } from '../config/supabase';
import type { LineItemInput } from '../types';
import { upsertCustomer } from './customers';

interface CreateReceiptParams {
  customerName: string;
  customerPhone: string;
  customerId?: string;
  type: 'buy' | 'sell';
  subtotal: number;
  signatureUri?: string | null;
  workerId: string;
  notes?: string;
  lineItems: LineItemInput[];
}

export async function createReceipt(params: CreateReceiptParams) {
  // Upsert customer record
  const customer = params.customerId
    ? { id: params.customerId }
    : await upsertCustomer(params.customerName, params.customerPhone);

  // Insert receipt
  const { data: receipt, error: receiptError } = await supabase
    .from('receipts')
    .insert({
      receipt_number: '', // auto-generated by trigger
      customer_name: params.customerName,
      customer_phone: params.customerPhone,
      customer_id: customer.id,
      type: params.type,
      subtotal: params.subtotal,
      signature_uri: params.signatureUri,
      worker_id: params.workerId,
      notes: params.notes,
    })
    .select()
    .single();

  if (receiptError) throw receiptError;

  // Insert line items
  const lineItemRows = params.lineItems.map((item) => ({
    receipt_id: receipt.id,
    metal_id: item.metalId,
    metal_name: item.metalName,
    weight: item.weight,
    gross_weight: item.grossWeight ?? null,
    tare_weight: item.tareWeight ?? null,
    price_per_lb: item.pricePerLb,
    original_price_per_lb: item.originalPricePerLb,
    is_price_override: item.isPriceOverride,
    override_approved_by: item.overrideApprovedBy,
    total: item.total,
  }));

  const { error: lineItemsError } = await supabase
    .from('line_items')
    .insert(lineItemRows);

  if (lineItemsError) throw lineItemsError;

  return receipt;
}

export async function fetchReceipts(
  workerId?: string,
  startDate?: string,
  endDate?: string
) {
  let query = supabase
    .from('receipts')
    .select('*, line_items(*)')
    .order('created_at', { ascending: false });

  if (workerId) {
    query = query.eq('worker_id', workerId);
  }
  if (startDate) {
    query = query.gte('created_at', `${startDate}T00:00:00`);
  }
  if (endDate) {
    query = query.lte('created_at', `${endDate}T23:59:59`);
  }

  const { data, error } = await query;
  if (error) throw error;
  return data;
}

export async function fetchReceiptById(receiptId: string) {
  const { data, error } = await supabase
    .from('receipts')
    .select('*, line_items(*, metals(name, price_per_lb))')
    .eq('id', receiptId)
    .single();
  if (error) throw error;
  return data;
}
