-- Close a catalytic-converter compliance loophole.
--
-- set_receipt_compliance() (20260422000014) decides whether a buy is a
-- catalytic-converter transaction — and therefore gets the 60-day hold and the
-- cash-payment ban (NM 57-30-2.4) — ONLY from the receipt-level is_catalytic
-- flag or from typed converter serial numbers. Both are client-supplied. It
-- never consults the authoritative, durable metals.is_catalytic flag on the
-- line items. So a converter bought under a catalytic *metal* but with the
-- receipt checkbox unchecked and no serials typed slipped through with a 24h
-- hold and could be paid in cash.
--
-- The receipt-level BEFORE INSERT trigger can't see the line items (they're
-- inserted after the receipt), but create_receipt_with_items has both in scope.
-- Compute catalytic authoritatively from the line-item metals here and force
-- is_catalytic on the receipt insert, so the existing trigger applies the
-- correct hold + payment rule. (The legitimate client already forces payment to
-- 'check' and collects a VIN for catalytic metals; this is the server backstop
-- for a crafted or buggy client.)
--
-- Only the catalytic detection changes; the rest of the function is unchanged
-- from 20260612000003.

create or replace function public.create_receipt_with_items(
  p_receipt jsonb,
  p_line_items jsonb
)
returns public.receipts
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.receipts;
  v_cat_metal boolean;
begin
  -- SECURITY DEFINER bypasses RLS, so re-assert the company-scoping the
  -- line_items/receipts INSERT policies would normally enforce: a buy can only
  -- be attributed to a staffer in the caller's own company. (company_id itself
  -- is forced to the caller's company by the column default.)
  if not exists (
    select 1 from public.users
    where id = (p_receipt->>'worker_id')::uuid
      and company_id = public.current_company_id()
  ) then
    raise exception 'worker_id must be a member of the current company';
  end if;

  -- Authoritative catalytic detection: any line item whose metal is flagged
  -- catalytic forces the receipt's catalytic rules (60-day hold, check-only),
  -- regardless of the client-set is_catalytic flag or typed converter serials.
  select exists (
    select 1
    from jsonb_array_elements(p_line_items) as li
    join public.metals m on m.id = (li->>'metal_id')::uuid
    where m.is_catalytic
  ) into v_cat_metal;

  insert into public.receipts (
    receipt_number, customer_name, customer_phone, customer_id, type, subtotal,
    signature_uri, worker_id, notes, vehicle_plate, vehicle_description,
    vehicle_year, vehicle_make, vehicle_model, vehicle_color, seller_affirmed,
    seller_name, seller_dl_number, seller_state_of_issue, seller_dob,
    seller_address, seller_city, seller_state, seller_zip, seller_id_photo_uri,
    cat_converter_numbers, transport_vin, cat_converter_photo_uri,
    cat_title_photo_uri, payment_method, is_catalytic, seller_photo_uri,
    material_photo_uri
  )
  values (
    '', -- receipt_number is generated by the receipts_auto_number trigger
    p_receipt->>'customer_name',
    coalesce(p_receipt->>'customer_phone', ''),
    nullif(p_receipt->>'customer_id', '')::uuid,
    p_receipt->>'type',
    coalesce((p_receipt->>'subtotal')::numeric, 0),
    p_receipt->>'signature_uri',
    (p_receipt->>'worker_id')::uuid,
    p_receipt->>'notes',
    coalesce(p_receipt->>'vehicle_plate', ''),
    coalesce(p_receipt->>'vehicle_description', ''),
    coalesce(p_receipt->>'vehicle_year', ''),
    coalesce(p_receipt->>'vehicle_make', ''),
    coalesce(p_receipt->>'vehicle_model', ''),
    coalesce(p_receipt->>'vehicle_color', ''),
    coalesce((p_receipt->>'seller_affirmed')::boolean, false),
    coalesce(p_receipt->>'seller_name', ''),
    coalesce(p_receipt->>'seller_dl_number', ''),
    coalesce(p_receipt->>'seller_state_of_issue', ''),
    coalesce(p_receipt->>'seller_dob', ''),
    coalesce(p_receipt->>'seller_address', ''),
    coalesce(p_receipt->>'seller_city', ''),
    coalesce(p_receipt->>'seller_state', ''),
    coalesce(p_receipt->>'seller_zip', ''),
    p_receipt->>'seller_id_photo_uri',
    coalesce(p_receipt->>'cat_converter_numbers', ''),
    coalesce(p_receipt->>'transport_vin', ''),
    p_receipt->>'cat_converter_photo_uri',
    p_receipt->>'cat_title_photo_uri',
    coalesce(p_receipt->>'payment_method', 'cash'),
    coalesce((p_receipt->>'is_catalytic')::boolean, false) or v_cat_metal,
    p_receipt->>'seller_photo_uri',
    p_receipt->>'material_photo_uri'
  )
  returning * into v;

  insert into public.line_items (
    receipt_id, metal_id, metal_name, weight, gross_weight, tare_weight,
    price_per_lb, original_price_per_lb, is_price_override, override_approved_by,
    total, is_regulated, is_restricted
  )
  select
    v.id,
    (li->>'metal_id')::uuid,
    li->>'metal_name',
    (li->>'weight')::numeric,
    nullif(li->>'gross_weight', '')::numeric,
    nullif(li->>'tare_weight', '')::numeric,
    (li->>'price_per_lb')::numeric,
    (li->>'original_price_per_lb')::numeric,
    coalesce((li->>'is_price_override')::boolean, false),
    nullif(li->>'override_approved_by', '')::uuid,
    (li->>'total')::numeric,
    coalesce((li->>'is_regulated')::boolean, false),
    coalesce((li->>'is_restricted')::boolean, false)
  from jsonb_array_elements(p_line_items) as li;

  return v;
end;
$$;

revoke all on function public.create_receipt_with_items(jsonb, jsonb) from public;
grant execute on function public.create_receipt_with_items(jsonb, jsonb) to authenticated;
