-- Seller "no metal-theft conviction" attestation on the buy receipt.
--
-- NM's Sale of Recycled Metals Act (§57-30-5) requires the seller to attest, in
-- addition to lawful ownership, that they have not been convicted of metal
-- theft. The app captured ownership (seller_affirmed) but not this — add it.
--
-- ⚠️ BUILD-VERIFIED ONLY: this redefines create_receipt_with_items (the atomic
-- receipt-creation RPC). It reproduces the existing function verbatim and only
-- adds seller_no_theft_affirmed to the insert. It MUST be applied + tested
-- against a live DB (create a normal buy AND a catalytic buy → confirm both
-- save, and the new column persists) before it's relied on in production.
--
-- The immutability trigger (enforce_receipt_immutability) is intentionally NOT
-- touched here — the new column is set once at insert and never updated, so
-- freezing it is a low-priority follow-up to do when the change is testable.

alter table public.receipts
  add column if not exists seller_no_theft_affirmed boolean not null default false;

create or replace function public.create_receipt_with_items(
  p_receipt jsonb,
  p_line_items jsonb
)
returns public.receipts
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.receipts;
begin
  if not exists (
    select 1 from public.users
    where id = (p_receipt->>'worker_id')::uuid
      and company_id = public.current_company_id()
  ) then
    raise exception 'worker_id must be a member of the current company';
  end if;

  insert into public.receipts (
    receipt_number, customer_name, customer_phone, customer_id, type, subtotal,
    signature_uri, worker_id, notes, vehicle_plate, vehicle_description,
    vehicle_year, vehicle_make, vehicle_model, vehicle_color, seller_affirmed,
    seller_no_theft_affirmed,
    seller_name, seller_dl_number, seller_state_of_issue, seller_dob,
    seller_address, seller_city, seller_state, seller_zip, seller_id_photo_uri,
    cat_converter_numbers, transport_vin, cat_converter_photo_uri,
    cat_title_photo_uri, payment_method, is_catalytic, seller_photo_uri,
    material_photo_uri
  )
  values (
    '', -- receipt_number is generated by the receipts_auto_number trigger
    p_receipt->>'customer_name',
    coalesce(p_receipt->>'customer_phone', ''),
    nullif(p_receipt->>'customer_id', '')::uuid,
    p_receipt->>'type',
    coalesce((p_receipt->>'subtotal')::numeric, 0),
    p_receipt->>'signature_uri',
    (p_receipt->>'worker_id')::uuid,
    p_receipt->>'notes',
    coalesce(p_receipt->>'vehicle_plate', ''),
    coalesce(p_receipt->>'vehicle_description', ''),
    coalesce(p_receipt->>'vehicle_year', ''),
    coalesce(p_receipt->>'vehicle_make', ''),
    coalesce(p_receipt->>'vehicle_model', ''),
    coalesce(p_receipt->>'vehicle_color', ''),
    coalesce((p_receipt->>'seller_affirmed')::boolean, false),
    coalesce((p_receipt->>'seller_no_theft_affirmed')::boolean, false),
    coalesce(p_receipt->>'seller_name', ''),
    coalesce(p_receipt->>'seller_dl_number', ''),
    coalesce(p_receipt->>'seller_state_of_issue', ''),
    coalesce(p_receipt->>'seller_dob', ''),
    coalesce(p_receipt->>'seller_address', ''),
    coalesce(p_receipt->>'seller_city', ''),
    coalesce(p_receipt->>'seller_state', ''),
    coalesce(p_receipt->>'seller_zip', ''),
    p_receipt->>'seller_id_photo_uri',
    coalesce(p_receipt->>'cat_converter_numbers', ''),
    coalesce(p_receipt->>'transport_vin', ''),
    p_receipt->>'cat_converter_photo_uri',
    p_receipt->>'cat_title_photo_uri',
    coalesce(p_receipt->>'payment_method', 'cash'),
    coalesce((p_receipt->>'is_catalytic')::boolean, false),
    p_receipt->>'seller_photo_uri',
    p_receipt->>'material_photo_uri'
  )
  returning * into v;

  insert into public.line_items (
    receipt_id, metal_id, metal_name, weight, gross_weight, tare_weight,
    price_per_lb, original_price_per_lb, is_price_override, override_approved_by,
    total, is_regulated, is_restricted
  )
  select
    v.id,
    (li->>'metal_id')::uuid,
    li->>'metal_name',
    (li->>'weight')::numeric,
    nullif(li->>'gross_weight', '')::numeric,
    nullif(li->>'tare_weight', '')::numeric,
    (li->>'price_per_lb')::numeric,
    (li->>'original_price_per_lb')::numeric,
    coalesce((li->>'is_price_override')::boolean, false),
    nullif(li->>'override_approved_by', '')::uuid,
    (li->>'total')::numeric,
    coalesce((li->>'is_regulated')::boolean, false),
    coalesce((li->>'is_restricted')::boolean, false)
  from jsonb_array_elements(p_line_items) as li;

  return v;
end;
$$;

revoke all on function public.create_receipt_with_items(jsonb, jsonb) from public;
grant execute on function public.create_receipt_with_items(jsonb, jsonb) to authenticated;
